const skillGrid=document.querySelector('#skillGrid'),syllabusGrid=document.querySelector('#syllabusGrid'),unitList=document.querySelector('#unitList'),resourceGrid=document.querySelector('#resourceGrid'),search=document.querySelector('#search'),menuBtn=document.querySelector('#menuBtn');
const skills=[
 {t:'Comprensión oral',d:'Comprender discursos extensos, densos, rápidos y con información implícita, incluso con variedad de acentos y registros.',x:['Selección múltiple','Emparejamiento','Completar notas','Actitud e inferencia'],r:'https://www.bbc.co.uk/programmes/p02nq0gn/episodes/downloads'},
 {t:'Producción y coproducción oral',d:'Desarrollar ideas complejas e interactuar con flexibilidad, precisión, tacto y control del turno.',x:['Entrevista','Monólogo sostenido','Tarea colaborativa','Debate y presentación'],r:'https://www.cambridgeenglish.org/exams-and-tests/proficiency/preparation/'},
 {t:'Comprensión escrita',d:'Procesar textos largos y complejos atendiendo a estructura, postura, intención, alusiones y relaciones internas.',x:['Selección múltiple','Texto con huecos','Emparejamiento','Síntesis de fuentes'],r:'https://www.theguardian.com/long-reads'},
 {t:'Producción y coproducción escrita',d:'Redactar textos claros, fluidos y eficaces con género, registro, organización y matices adecuados.',x:['Ensayo','Artículo','Informe/propuesta','Reseña y correspondencia'],r:'https://writeandimprove.com/'},
 {t:'Mediación',d:'Transmitir y reconstruir información para otra persona, seleccionando, reorganizando y adaptando contenido y registro.',x:['Texto → oral','Texto → texto','Audio → oral','Español ↔ inglés'],r:'https://eoienglish.es/index.php/contenidos/c2/modelos-examen-c2'}
];
const syllabus=[
 ['Gramática de precisión',['Contraste temporal y aspectual','Modalidad, condición e hipótesis','Inversión y énfasis','Pasivas, causativas y estructuras de reporte','Subordinación, participios y nominalización']],
 ['Discurso y cohesión',['Referencia y elipsis','Conectores con matiz','Progresión temática','Concesión y contraste','Organización según género y destinatario']],
 ['Léxico y fraseología',['Colocaciones densas','Phrasal verbs y compuestos','Word formation','Idioms con control de registro','Connotación, polisemia y precisión semántica']],
 ['Fonología',['Word stress','Sentence stress y foco contrastivo','Chunking y ritmo','Weak forms y linking','Entonación para postura, reserva y cortesía']],
 ['Sociolingüística',['Registro formal, neutral e informal','Humor, ironía y eufemismo','Convenciones de género','Cortesía y distancia','Variedades y referencias culturales']],
 ['Estrategias',['Inferir sin detenerse','Planificar bajo tiempo','Reformular y reparar','Seleccionar información al mediar','Autoevaluar y reutilizar feedback']]
];
const units=[
 {t:'This is us',lf:'The present',v:'Feelings and emotions · self- adjectives and nouns',i:'Personality',exam:'RUE 1, 2, 6 · article/letter · Listening 1 · Speaking 1/3',chunks:['come across as','keep one’s feelings to oneself','painfully self-conscious','quietly self-assured','remain level-headed'],focus:'Distinguir rasgo estable, conducta temporal y cambio reciente sin perder naturalidad.',res:[['Pronunciación en contexto','https://youglish.com/pronounce/self-conscious/english'],['Identidad y lenguaje','https://www.ted.com/topics/identity']]},
 {t:'Wanderlust',lf:'Past forms · adverbs and adverbial phrases',v:'Travel · adverbs',i:'Making stories interesting',exam:'RUE 3, 4, 5 · essay/report · Listening 2 · Speaking 1/2',chunks:['venture off the beaten track','a gruelling journey','travel on a shoestring','by the time','oddly enough'],focus:'Narrar con perspectiva temporal, selección de detalle y evaluación, no como una cronología plana.',res:[['Travel vocabulary','https://dictionary.cambridge.org/topics/travelling/'],['Travel talks','https://www.ted.com/topics/travel']]},
 {t:'Ahead of the curve',lf:'Talking about the future · will, shall and would',v:'Phrasal verbs · noun collocations · at/in/on/under',i:'Innovation',exam:'RUE 2, 3, 4, 7 · review/article · Listening 1/4 · Speaking 1/3',chunks:['prove a game changer','be on the verge of','gain widespread acceptance','wear off','far-reaching implications'],focus:'Graduar predicciones y consecuencias sin presentar especulación como certeza.',res:[['Technology','https://www.ted.com/topics/technology'],['Future forms','https://dictionary.cambridge.org/grammar/british-grammar/future']]},
 {t:'Meeting in the middle',lf:'Modal verbs 1 · noun phrases and nominal clauses',v:'Partitives · uncountable nouns · closed compounds',i:'Negotiation',exam:'RUE 1, 6 · essay/letter · Listening 2/3 · Speaking 1/2',chunks:['reach common ground','make a concession','a sticking point','be open to compromise','strike a balance'],focus:'Negociar posibilidad, obligación y concesión manteniendo precisión y tacto interpersonal.',res:[['Negotiation talks','https://www.ted.com/topics/negotiation'],['Modal verbs','https://dictionary.cambridge.org/grammar/british-grammar/modality-introduction']]},
 {t:'News travels fast',lf:'Cohesion · demonstratives',v:'Neutral and sensationalist language · binomials',i:'Communication',exam:'RUE 1, 2, 4, 6 · article/report · Listening 4 · Speaking 1/3',chunks:['distort public understanding','withhold context','fuel speculation','hard and fast','frame the issue as'],focus:'Reconocer encuadre, carga emotiva, presuposiciones y cadenas de referencia en textos densos.',res:[['Media literacy','https://www.bbc.co.uk/bitesize/articles/z2gkqyc'],['Communication','https://www.ted.com/topics/communication']]},
 {t:'Highs and lows',lf:'Conditional clauses',v:'Expressions with pay · rise and fall',i:'Money and wealth',exam:'RUE 3, 4, 7 · essay/letter · Listening 1/2 · Speaking 1/2',chunks:['face a shortfall','bear the cost','pay dividends','a sharp downturn','had it not been for'],focus:'Construir hipótesis y contrafactuales complejos vinculando causas pasadas y consecuencias presentes.',res:[['Economics','https://www.ted.com/topics/economics'],['Conditionals','https://dictionary.cambridge.org/grammar/british-grammar/conditionals-if']]},
 {t:'Working it out',lf:'Modal verbs 2 · adjectives and fixed expressions',v:'Deduction/investigation · confusion/deceit',i:'Mystery',exam:'RUE 2, 4, 6 · review/article · Listening 3 · Speaking 1/2',chunks:['shed light on','rule out a possibility','jump to conclusions','conceal the truth','a plausible explanation'],focus:'Separar hecho, indicio e hipótesis y expresar grados finos de certeza retrospectiva.',res:[['Crime vocabulary','https://dictionary.cambridge.org/topics/crime-and-criminals/'],['Mystery stories','https://www.bbc.co.uk/learningenglish/english/features/drama']]},
 {t:'Human impact',lf:'Comparatives · expressing contrast',v:'Environment collocations',i:'Noticing similarities and differences',exam:'RUE 3, 4, 5 · essay/letter · Listening 2/4 · Speaking 1/3',chunks:['pose a threat to','offset emissions','no less effective','by comparison','yield broader benefits'],focus:'Comparar con criterios explícitos, límites y consecuencias; evitar afirmaciones absolutas.',res:[['Environment','https://www.ted.com/topics/environment'],['Climate vocabulary','https://dictionary.cambridge.org/topics/climate-and-environment/']]},
 {t:'By design',lf:'Concession, contrast, purpose and reason · passive/causative',v:'by/in/out of · art and architecture',i:'Art and creativity',exam:'RUE 1, 2, 7 · essay/review · Listening 2/3 · Speaking 1/2',chunks:['serve a dual purpose','have something redesigned','a bold departure from','despite initial misgivings','be widely acclaimed'],focus:'Explicar decisiones de diseño, agencia y efecto usando concesión y estructuras impersonales.',res:[['Design','https://www.ted.com/topics/design'],['Art vocabulary','https://dictionary.cambridge.org/topics/arts-and-crafts/']]},
 {t:'Adaptation',lf:'Inversion · emphasis and cleft sentences',v:'Books and films · similes',i:'From literature',exam:'RUE 1, 3, 4, 5 · essay/review · Listening 4 · Speaking 1/3',chunks:['remain faithful to','stand on its own merits','bring a character to life','rarely does…','what sets it apart is…'],focus:'Usar énfasis marcado con intención discursiva, no insertar inversión como decoración.',res:[['Literature','https://www.ted.com/topics/literature'],['Inversion','https://dictionary.cambridge.org/grammar/british-grammar/inversion']]},
 {t:'Talk of the town',lf:'Reporting structures 1 and 2',v:'City dwelling · problems and solutions',i:'Talk and tell',exam:'RUE 2, 4, 7 · essay/report · Listening 1 · Speaking 1/3',chunks:['is understood to have','acknowledge shortcomings','raise concerns about','ease congestion','urban sprawl'],focus:'Atribuir afirmaciones y graduar distancia, certeza y responsabilidad de la fuente.',res:[['Cities','https://www.ted.com/topics/cities'],['Reported speech','https://dictionary.cambridge.org/grammar/british-grammar/reported-speech-indirect-speech']]},
 {t:'On the right track',lf:'Participle clauses · verb patterns',v:'Health and fitness · multi-word verbs',i:'Sports',exam:'RUE 1, 3, 4, 5 · letter/report · Listening 3 · Speaking 1/3',chunks:['push oneself too far','show signs of fatigue','make a full recovery','having taken into account','viewed in isolation'],focus:'Comprimir información sin crear participios ambiguos y controlar los patrones verbales.',res:[['Health','https://www.ted.com/topics/health'],['Participle clauses','https://dictionary.cambridge.org/grammar/british-grammar/participle-clauses']]}
];
const resources=[
 ['OFICIAL','Currículo C2 · Región de Murcia','Ordenación, objetivos, competencias, contenidos y evaluación del nivel.','https://noticias.juridicas.com/base_datos/CCAA/670181-d-54-2020-de-2-jul-ca-murcia-ordenacion-de-las-ensenanzas-de-idiomas-de-regimen.html'],
 ['OFICIAL','Modelos C2 de Murcia','Archivo de pruebas publicadas y práctica por destrezas.','https://eoienglish.es/index.php/contenidos/c2/modelos-examen-c2'],
 ['LÉXICO','Cambridge Dictionary','Definiciones, registro, colocaciones, IPA y audio UK/US.','https://dictionary.cambridge.org/'],
 ['PRONUNCIACIÓN','YouGlish','Chunks pronunciados en múltiples contextos reales.','https://youglish.com/'],
 ['LISTENING','BBC Sounds','Podcasts, entrevistas, documentales y registros variados.','https://www.bbc.co.uk/sounds'],
 ['INPUT + TRANSCRIPT','TED Talks','Charlas temáticas con subtítulos y transcripción interactiva.','https://www.ted.com/talks'],
 ['WRITING','Write & Improve','Práctica de escritura y ciclos de revisión.','https://writeandimprove.com/'],
 ['CORPUS','SKELL','Ejemplos, colocaciones y concordancias en contexto.','https://skell.sketchengine.eu/'],
 ['CERTIFICACIÓN','Normativa Murcia 2025–26','Marco vigente de matrícula y certificación C2 en la Región de Murcia.','https://www.borm.es/services/anuncio/840845/pdf']
];
skillGrid.innerHTML=skills.map((s,i)=>`<article class="skill-card"><span class="num">0${i+1}</span><h3>${s.t}</h3><p>${s.d}</p><ul>${s.x.map(x=>`<li>${x}</li>`).join('')}</ul><a href="${s.r}" target="_blank" rel="noopener">Recurso ↗</a></article>`).join('');
syllabusGrid.innerHTML=syllabus.map(s=>`<article class="syllabus-card"><h3>${s[0]}</h3><ul>${s[1].map(x=>`<li>${x}</li>`).join('')}</ul></article>`).join('');
function drawUnits(q=''){const query=q.toLowerCase().trim();unitList.innerHTML=units.map((u,i)=>{const text=Object.values(u).flat().join(' ').toLowerCase(),hidden=query&&!text.includes(query);return `<details class="unit" ${hidden?'hidden':''}><summary><span class="unit-num">UNIT ${String(i+1).padStart(2,'0')}</span><div><h3>${u.t}</h3><p>${u.lf} · ${u.v}</p></div></summary><div class="unit-body"><article class="unit-block"><h4>Qué estudiar</h4><p><b>Language Focus:</b> ${u.lf}</p><p><b>Vocabulary:</b> ${u.v}</p><p><b>Idioms:</b> ${u.i}</p><p><b>Dificultad de la unidad:</b> ${u.focus}</p></article><article class="unit-block"><h4>Tipos de ejercicio del manual</h4><p>${u.exam}</p><h4>Vocabulario y expresiones activas</h4><div class="tags">${u.chunks.map(x=>`<span>${x}</span>`).join('')}</div><div class="links">${u.res.map(r=>`<a href="${r[1]}" target="_blank" rel="noopener">${r[0]} ↗</a>`).join('')}</div></article></div></details>`}).join('')}
drawUnits();search.addEventListener('input',e=>drawUnits(e.target.value));
resourceGrid.innerHTML=resources.map(r=>`<a class="resource" href="${r[3]}" target="_blank" rel="noopener"><small>${r[0]}</small><b>${r[1]}</b><p>${r[2]}</p></a>`).join('');
menuBtn.onclick=()=>document.querySelector('.site-header nav').classList.toggle('open');document.querySelectorAll('.site-header nav a').forEach(a=>a.onclick=()=>document.querySelector('.site-header nav').classList.remove('open'));
